// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCL5mf6AEuUbFUd8cAJ5Zrs8LgLXm08SD0',
    appId: '1:605430640603:web:2ff8d163f5613f353901fe',
    messagingSenderId: '605430640603',
    projectId: 'medicata-786',
    authDomain: 'medicata-786.firebaseapp.com',
    storageBucket: 'medicata-786.firebasestorage.app',
    measurementId: 'G-T3GLFNDG91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHUFCzjj6jzbEcbBYcNJj4ziBIiDSJCbE',
    appId: '1:605430640603:android:cb1b8059d6f857a53901fe',
    messagingSenderId: '605430640603',
    projectId: 'medicata-786',
    storageBucket: 'medicata-786.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUf6yzldZWznLa0qNd3pv1Wq8wiECUujw',
    appId: '1:605430640603:ios:7e636f5c1b9d5a173901fe',
    messagingSenderId: '605430640603',
    projectId: 'medicata-786',
    storageBucket: 'medicata-786.firebasestorage.app',
    iosBundleId: 'com.example.medicata',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUf6yzldZWznLa0qNd3pv1Wq8wiECUujw',
    appId: '1:605430640603:ios:7e636f5c1b9d5a173901fe',
    messagingSenderId: '605430640603',
    projectId: 'medicata-786',
    storageBucket: 'medicata-786.firebasestorage.app',
    iosBundleId: 'com.example.medicata',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCL5mf6AEuUbFUd8cAJ5Zrs8LgLXm08SD0',
    appId: '1:605430640603:web:57a4111bb6383c953901fe',
    messagingSenderId: '605430640603',
    projectId: 'medicata-786',
    authDomain: 'medicata-786.firebaseapp.com',
    storageBucket: 'medicata-786.firebasestorage.app',
    measurementId: 'G-639V4N89GQ',
  );
}
